"""Add timecard to scheduleshift

Revision ID: 0380d444047e
Revises: 7f5f9be011f6
Create Date: 2021-02-02 02:11:25.977558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0380d444047e'
down_revision = '7f5f9be011f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_shift', sa.Column('time_card_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedule_shift', 'time_card', ['time_card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_shift', type_='foreignkey')
    op.drop_column('schedule_shift', 'time_card_id')
    # ### end Alembic commands ###
