"""empty message

Revision ID: 1146bd7320ec
Revises: 93a3a5e4689b
Create Date: 2021-01-11 13:52:44.144938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1146bd7320ec'
down_revision = '93a3a5e4689b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_info', sa.Column('hourly_rate', sa.Numeric(), nullable=True))
    op.drop_column('employee_info', 'hourly_pay')
    op.add_column('time_card', sa.Column('total_payment', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_card', 'total_payment')
    op.add_column('employee_info', sa.Column('hourly_pay', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('employee_info', 'hourly_rate')
    # ### end Alembic commands ###
