"""Move customer url out of user object. Add hybrid property to get customer url for a user

Revision ID: 126c2c3e1c8e
Revises: 320b7dcd85a6
Create Date: 2021-09-03 20:43:22.095847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '126c2c3e1c8e'
down_revision = '320b7dcd85a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor_info', sa.Column('dwolla_customer_url', sa.String(length=255), nullable=True))
    op.drop_constraint('contractor_info_ssn_key', 'contractor_info', type_='unique')
    op.drop_column('contractor_info', 'ssn')
    op.drop_column('contractor_info', 'city')
    op.drop_column('contractor_info', 'state')
    op.drop_column('contractor_info', 'need_info')
    op.drop_column('contractor_info', 'longitude')
    op.drop_column('contractor_info', 'zip_code')
    op.drop_column('contractor_info', 'latitude')
    op.drop_column('contractor_info', 'address')
    op.drop_column('time_card', 'transaction_id')
    op.drop_column('time_card', 'payout_id')
    op.drop_column('time_card', 'approved')
    op.drop_column('user', 'dwolla_customer_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dwolla_customer_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('time_card', sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('time_card', sa.Column('payout_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('time_card', sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('contractor_info', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('contractor_info', sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('contractor_info', sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('contractor_info', sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('contractor_info', sa.Column('need_info', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('contractor_info', sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('contractor_info', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('contractor_info', sa.Column('ssn', sa.VARCHAR(length=9), autoincrement=False, nullable=True))
    op.create_unique_constraint('contractor_info_ssn_key', 'contractor_info', ['ssn'])
    op.drop_column('contractor_info', 'dwolla_customer_url')
    # ### end Alembic commands ###
