"""empty message

Revision ID: 1a03b5e6e199
Revises: 1146bd7320ec
Create Date: 2021-01-11 16:52:31.355551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a03b5e6e199'
down_revision = '1146bd7320ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('time_break', sa.Numeric(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('total_payment', sa.Numeric(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_card')
    # ### end Alembic commands ###
