"""Add long and lat to employee info

Revision ID: 1e7e98778744
Revises: 4df58776eb0c
Create Date: 2021-01-22 15:15:37.194898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7e98778744'
down_revision = '4df58776eb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_info', sa.Column('latitude', sa.Float(precision=52), nullable=True))
    op.add_column('employee_info', sa.Column('longitude', sa.Float(precision=52), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_info', 'longitude')
    op.drop_column('employee_info', 'latitude')
    # ### end Alembic commands ###
