"""empty message

Revision ID: 1f13a9c80cf8
Revises: 216061130274
Create Date: 2021-01-16 10:41:27.578448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f13a9c80cf8'
down_revision = '216061130274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_card', sa.Column('denied', sa.Boolean(), nullable=True))
    op.add_column('time_card', sa.Column('transaction_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_card', 'transaction_id')
    op.drop_column('time_card', 'denied')
    # ### end Alembic commands ###
