"""empty message

Revision ID: 216061130274
Revises: fe9514fbeda7
Create Date: 2021-01-15 16:29:45.625783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '216061130274'
down_revision = 'fe9514fbeda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_card', sa.Column('total_time', sa.Numeric(), nullable=True))
    op.drop_column('time_card', 'time_out')
    op.drop_column('time_card', 'time_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_card', sa.Column('time_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('time_card', sa.Column('time_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('time_card', 'total_time')
    # ### end Alembic commands ###
