"""empty message

Revision ID: 2202b3d1aaaa
Revises: f36449bb7216
Create Date: 2021-01-18 18:39:02.542651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2202b3d1aaaa'
down_revision = 'f36449bb7216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_card', sa.Column('payout_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_card', 'payout_id')
    # ### end Alembic commands ###
