"""empty message

Revision ID: 2744a4bbf16a
Revises: 4657b93f1639
Create Date: 2021-07-08 16:59:15.724514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2744a4bbf16a'
down_revision = '4657b93f1639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ssn', sa.String(length=9), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('longitude', sa.Float(precision=52), nullable=True),
    sa.Column('latitude', sa.Float(precision=52), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(), nullable=True),
    sa.Column('need_info', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ssn')
    )
    op.drop_table('employee_info')
    op.add_column('job', sa.Column('contractor_manager_id', sa.Integer(), nullable=True))
    op.drop_constraint('job_employee_manager_id_fkey', 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'user', ['contractor_manager_id'], ['id'])
    op.drop_column('job', 'employee_manager_id')
    op.drop_column('organization', 'primary_contact_last_name')
    op.drop_column('organization', 'primary_contact_first_name')
    op.drop_column('organization', 'primary_contact_phone')
    op.drop_column('organization', 'primary_contact_email')
    op.add_column('schedule_shift', sa.Column('contractor_id', sa.Integer(), nullable=True))
    op.drop_constraint('schedule_shift_employee_id_fkey', 'schedule_shift', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_shift', 'user', ['contractor_id'], ['id'])
    op.drop_column('schedule_shift', 'employee_id')
    op.add_column('time_card', sa.Column('contractor_id', sa.Integer(), nullable=True))
    op.drop_constraint('time_card_employee_id_fkey', 'time_card', type_='foreignkey')
    op.create_foreign_key(None, 'time_card', 'user', ['contractor_id'], ['id'])
    op.drop_column('time_card', 'employee_id')
    op.add_column('time_clock', sa.Column('contractor_id', sa.Integer(), nullable=True))
    op.drop_constraint('time_clock_employee_id_fkey', 'time_clock', type_='foreignkey')
    op.create_foreign_key(None, 'time_clock', 'user', ['contractor_id'], ['id'])
    op.drop_column('time_clock', 'employee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_clock', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'time_clock', type_='foreignkey')
    op.create_foreign_key('time_clock_employee_id_fkey', 'time_clock', 'user', ['employee_id'], ['id'])
    op.drop_column('time_clock', 'contractor_id')
    op.add_column('time_card', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'time_card', type_='foreignkey')
    op.create_foreign_key('time_card_employee_id_fkey', 'time_card', 'user', ['employee_id'], ['id'])
    op.drop_column('time_card', 'contractor_id')
    op.add_column('schedule_shift', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schedule_shift', type_='foreignkey')
    op.create_foreign_key('schedule_shift_employee_id_fkey', 'schedule_shift', 'user', ['employee_id'], ['id'])
    op.drop_column('schedule_shift', 'contractor_id')
    op.add_column('organization', sa.Column('primary_contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organization', sa.Column('primary_contact_phone', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('organization', sa.Column('primary_contact_first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organization', sa.Column('primary_contact_last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('job', sa.Column('employee_manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key('job_employee_manager_id_fkey', 'job', 'user', ['employee_manager_id'], ['id'])
    op.drop_column('job', 'contractor_manager_id')
    op.create_table('employee_info',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ssn', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hourly_rate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('need_info', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], name='employee_info_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='employee_info_pkey'),
    sa.UniqueConstraint('ssn', name='employee_info_ssn_key')
    )
    op.drop_table('contractor_info')
    # ### end Alembic commands ###
