"""empty message

Revision ID: 2744a4bbf16a
Revises: 4657b93f1639
Create Date: 2021-07-08 16:59:15.724514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2744a4bbf16a'
down_revision = '4657b93f1639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('employee_info', 'contractor_info')
    op.execute('ALTER TABLE contractor_info RENAME CONSTRAINT employee_info_id_fkey TO contractor_info_id_fkey')
    op.execute('ALTER TABLE contractor_info RENAME CONSTRAINT employee_info_pkey TO contractor_info_pkey')
    op.execute('ALTER TABLE contractor_info RENAME CONSTRAINT employee_info_ssn_key TO contractor_info_ssn_key')

    op.alter_column('job', 'employee_manager_id', existing_type=sa.Integer, existing_nullable=False, new_column_name='contractor_manager_id')
    op.execute('ALTER TABLE job RENAME CONSTRAINT job_employee_manager_id_fkey TO job_contractor_manager_id_fkey')

    op.drop_column('organization', 'primary_contact_last_name')
    op.drop_column('organization', 'primary_contact_first_name')
    op.drop_column('organization', 'primary_contact_phone')
    op.drop_column('organization', 'primary_contact_email')

    op.alter_column('schedule_shift', 'employee_id', existing_type=sa.Integer, existing_nullable=False, new_column_name='contractor_id')
    op.execute('ALTER TABLE schedule_shift RENAME CONSTRAINT schedule_shift_employee_id_fkey TO schedule_shift_contractor_id_fkey')

    op.alter_column('time_card', 'employee_id', existing_type=sa.Integer, existing_nullable=False, new_column_name='contractor_id')
    op.execute('ALTER TABLE time_card RENAME CONSTRAINT time_card_employee_id_fkey TO time_card_contractor_id_fkey')

    op.alter_column('time_clock', 'employee_id', existing_type=sa.Integer, existing_nullable=False, new_column_name='contractor_id')
    op.execute('ALTER TABLE time_clock RENAME CONSTRAINT time_clock_employee_id_fkey TO time_clock_contractor_id_fkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE time_clock RENAME CONSTRAINT time_clock_contractor_id_fkey TO time_clock_employee_id_fkey')
    op.alter_column('time_clock', 'contractor_id', existing_type=sa.Integer, existing_nullable=False, new_column_name='employee_id')

    op.execute('ALTER TABLE time_card RENAME CONSTRAINT time_card_contractor_id_fkey TO time_card_employee_id_fkey')
    op.alter_column('time_card', 'contractor_id', existing_type=sa.Integer, existing_nullable=False, new_column_name='employee_id')

    op.execute('ALTER TABLE schedule_shift RENAME CONSTRAINT schedule_shift_contractor_id_fkey TO schedule_shift_employee_id_fkey')
    op.alter_column('schedule_shift', 'contractor_id', existing_type=sa.Integer, existing_nullable=False, new_column_name='employee_id')

    op.add_column('organization', sa.Column('primary_contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organization', sa.Column('primary_contact_phone', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('organization', sa.Column('primary_contact_first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organization', sa.Column('primary_contact_last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    
    op.execute('ALTER TABLE job RENAME CONSTRAINT job_contractor_manager_id_fkey TO job_employee_manager_id_fkey')
    op.alter_column('job', 'contractor_manager_id', existing_type=sa.Integer, existing_nullable=False, new_column_name='employee_manager_id')

    op.execute('ALTER TABLE contractor_info RENAME CONSTRAINT contractor_info_id_fkey TO employee_info_id_fkey')
    op.execute('ALTER TABLE contractor_info RENAME CONSTRAINT contractor_info_pkey TO employee_info_pkey')
    op.execute('ALTER TABLE contractor_info RENAME CONSTRAINT contractor_info_ssn_key TO employee_info_ssn_key')
    op.rename_table('contractor_info', 'employee_info')
    # ### end Alembic commands ###
