"""Messenger

Revision ID: 28da187eabc2
Revises: cce7b16683ea
Create Date: 2021-01-12 02:32:10.440023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28da187eabc2'
down_revision = 'cce7b16683ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('time_break', sa.Numeric(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('total_payment', sa.Numeric(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('time_cards')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_break', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_payment', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], name='time_cards_employee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='time_cards_pkey')
    )
    op.drop_table('time_card')
    # ### end Alembic commands ###
