"""Add conversations

Revision ID: 29c90bc04ffa
Revises: 386fcabba7cf
Create Date: 2021-01-22 19:37:04.094384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c90bc04ffa'
down_revision = '386fcabba7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_conversation')
    op.drop_column('user_conversation', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_conversation', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_table('message_conversation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name='message_conversation_conversation_id_fkey'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='message_conversation_message_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='message_conversation_pkey')
    )
    # ### end Alembic commands ###
