"""Add conversations

Revision ID: 386fcabba7cf
Revises: 93d82c65a268
Create Date: 2021-01-22 19:25:09.850353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386fcabba7cf'
down_revision = '93d82c65a268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'conversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'conversation_id')
    # ### end Alembic commands ###
