"""Add active flag on shift

Revision ID: 3c4f12338b5e
Revises: f57b5bd952b4
Create Date: 2022-01-10 13:28:20.886052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c4f12338b5e"
down_revision = "f57b5bd952b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedule_shift", sa.Column("active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule_shift", "active")
    # ### end Alembic commands ###
