"""Add minimum wage to Organization

Revision ID: 3c9d0d187051
Revises: 61aff9b2650b
Create Date: 2021-09-21 16:16:54.474607

"""
from alembic import op
import sqlalchemy as sa
from app.models import Organization
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = "3c9d0d187051"
down_revision = "61aff9b2650b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    session = Session(bind=conn)
    op.add_column("organization", sa.Column("minimum_wage", sa.Numeric()))
    for item in session.query(Organization).filter_by(minimum_wage=None):
        item.minimum_wage = 7.5
    session.commit()
    op.alter_column("organization", "minimum_wage", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization", "minimum_wage")
    # ### end Alembic commands ###
