"""Dev Upgrade

Revision ID: 3cf8b049c1d8
Revises: 042d5ac8a66d
Create Date: 2021-08-25 17:45:05.502296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf8b049c1d8'
down_revision = '042d5ac8a66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('dwolla_customer_url', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('dwolla_customer_url', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('fs_uniquifier', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'user', ['fs_uniquifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'fs_uniquifier')
    op.drop_column('user', 'dwolla_customer_url')
    op.drop_column('organization', 'dwolla_customer_url')
    # ### end Alembic commands ###
