"""empty message

Revision ID: 4df58776eb0c
Revises: c25f79bafa2d
Create Date: 2021-01-21 02:56:34.270053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df58776eb0c'
down_revision = 'c25f79bafa2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('organization_manager_id', sa.Integer(), nullable=True))
    op.drop_constraint('job_organizational_manager_id_fkey', 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'user', ['organization_manager_id'], ['id'])
    op.drop_column('job', 'organizational_manager_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('organizational_manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key('job_organizational_manager_id_fkey', 'job', 'user', ['organizational_manager_id'], ['id'])
    op.drop_column('job', 'organization_manager_id')
    # ### end Alembic commands ###
