"""empty message

Revision ID: 5ae468908700
Revises: 2202b3d1aaaa
Create Date: 2021-01-19 23:01:26.459638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae468908700'
down_revision = '2202b3d1aaaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('latitude', sa.Float(precision=64), nullable=True))
    op.add_column('job', sa.Column('longitude', sa.Float(precision=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'longitude')
    op.drop_column('job', 'latitude')
    # ### end Alembic commands ###
