"""Refactor dwolla status

Revision ID: 6196760e4e73
Revises: 6dde308a631d
Create Date: 2021-10-27 21:35:49.328083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6196760e4e73"
down_revision = "6dde308a631d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contractor_info",
        sa.Column("dwolla_customer_status", sa.String(length=10), nullable=True),
    )
    op.drop_column("contractor_info", "dwolla_status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contractor_info",
        sa.Column(
            "dwolla_status", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("contractor_info", "dwolla_customer_status")
    # ### end Alembic commands ###
