"""Move ManagerReference to ManagerInfo. Prevent dwolla_customer_url from showing up twice.

Revision ID: 61aff9b2650b
Revises: 126c2c3e1c8e
Create Date: 2021-09-10 20:58:59.764952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61aff9b2650b'
down_revision = '126c2c3e1c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager_info',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('reference_number')
    )
    op.drop_table('manager_reference')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('manager_reference',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reference_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='manager_reference_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='manager_reference_pkey'),
    sa.UniqueConstraint('reference_number', name='manager_reference_reference_number_key')
    )
    op.drop_table('manager_info')
    # ### end Alembic commands ###
