"""Add timecard to scheduleshift

Revision ID: 663fa9bbf594
Revises: 0380d444047e
Create Date: 2021-02-02 03:33:34.459505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663fa9bbf594'
down_revision = '0380d444047e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_shift', sa.Column('timecard_id', sa.Integer(), nullable=True))
    op.drop_constraint('schedule_shift_time_card_id_fkey', 'schedule_shift', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_shift', 'time_card', ['timecard_id'], ['id'])
    op.drop_column('schedule_shift', 'time_card_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_shift', sa.Column('time_card_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'schedule_shift', type_='foreignkey')
    op.create_foreign_key('schedule_shift_time_card_id_fkey', 'schedule_shift', 'time_card', ['time_card_id'], ['id'])
    op.drop_column('schedule_shift', 'timecard_id')
    # ### end Alembic commands ###
