"""Check info

Revision ID: 7f5f9be011f6
Revises: 29c90bc04ffa
Create Date: 2021-01-24 01:00:27.574350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f5f9be011f6'
down_revision = '29c90bc04ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_info', sa.Column('need_info', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_info', 'need_info')
    # ### end Alembic commands ###
