"""empty message

Revision ID: 7f73c0aa089c
Revises: 1f13a9c80cf8
Create Date: 2021-01-16 18:45:07.377457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f73c0aa089c'
down_revision = '1f13a9c80cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_card', sa.Column('fees_payment', sa.Numeric(), nullable=True))
    op.add_column('time_card', sa.Column('wage_payment', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_card', 'wage_payment')
    op.drop_column('time_card', 'fees_payment')
    # ### end Alembic commands ###
