"""Restructured shifts for both timeclock and schedule

Revision ID: 817e58887cd6
Revises: c4b3bcb55b78
Create Date: 2021-01-02 18:21:47.246270

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '817e58887cd6'
down_revision = 'c4b3bcb55b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_clock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_begin', sa.DateTime(), nullable=True),
    sa.Column('action', sa.Enum('clock_in', 'clock_out', 'start_break', 'end_break', name='timeclockaction'), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('time_clock_shift')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_clock_shift',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time_begin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], name='time_clock_shift_employee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='time_clock_shift_pkey')
    )
    op.drop_table('time_clock')
    # ### end Alembic commands ###
