"""empty message

Revision ID: 93a3a5e4689b
Revises: 2e41c2ac216b
Create Date: 2021-01-11 13:51:02.572246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a3a5e4689b'
down_revision = '2e41c2ac216b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_info', sa.Column('hourly_pay', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_info', 'hourly_pay')
    # ### end Alembic commands ###
