"""Add conversations

Revision ID: 93d82c65a268
Revises: c9f8855aff0f
Create Date: 2021-01-22 19:04:38.149536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d82c65a268'
down_revision = 'c9f8855aff0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('message_conversation_id_fkey', 'message', type_='foreignkey')
    op.drop_column('message', 'conversation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('message_conversation_id_fkey', 'message', 'conversation', ['conversation_id'], ['id'])
    op.drop_table('message_conversation')
    # ### end Alembic commands ###
