"""Restructured shifts for both timeclock and schedule

Revision ID: 9b3493335c8d
Revises: 817e58887cd6
Create Date: 2021-01-02 18:35:07.429749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b3493335c8d'
down_revision = '817e58887cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_clock', sa.Column('time', sa.DateTime(), nullable=True))
    op.drop_column('time_clock', 'time_begin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_clock', sa.Column('time_begin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('time_clock', 'time')
    # ### end Alembic commands ###
