"""Added replaced primary manager in Organization with primary contact info

Revision ID: 9d76af213994
Revises: 05dcc3df8e5f
Create Date: 2021-01-04 03:10:23.385048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d76af213994'
down_revision = '05dcc3df8e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('primary_contact_email', sa.String(length=255), nullable=True))
    op.add_column('organization', sa.Column('primary_contact_first_name', sa.String(length=255), nullable=True))
    op.add_column('organization', sa.Column('primary_contact_last_name', sa.String(length=255), nullable=True))
    op.add_column('organization', sa.Column('primary_contact_phone', sa.String(length=10), nullable=True))
    op.drop_constraint('organization_primary_manager_fkey', 'organization', type_='foreignkey')
    op.drop_column('organization', 'primary_manager')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('primary_manager', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('organization_primary_manager_fkey', 'organization', 'user', ['primary_manager'], ['id'])
    op.drop_column('organization', 'primary_contact_phone')
    op.drop_column('organization', 'primary_contact_last_name')
    op.drop_column('organization', 'primary_contact_first_name')
    op.drop_column('organization', 'primary_contact_email')
    # ### end Alembic commands ###
