"""Typo in job

Revision ID: a17cb822d259
Revises: 9d76af213994
Create Date: 2021-01-04 03:21:45.051983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17cb822d259'
down_revision = '9d76af213994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('organizational_manager_id', sa.Integer(), nullable=True))
    op.drop_constraint('job_orgizational_manager_id_fkey', 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'user', ['organizational_manager_id'], ['id'])
    op.drop_column('job', 'orgizational_manager_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('orgizational_manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key('job_orgizational_manager_id_fkey', 'job', 'user', ['orgizational_manager_id'], ['id'])
    op.drop_column('job', 'organizational_manager_id')
    # ### end Alembic commands ###
