"""Add subscription table and fields to organization

Revision ID: a98d65884513
Revises: 5faf4f716cc9
Create Date: 2022-02-05 18:05:59.016534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a98d65884513"
down_revision = "5faf4f716cc9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_tier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("monthly_rate", sa.Numeric(), nullable=True),
        sa.Column("annual", sa.Boolean(), nullable=True),
        sa.Column("num_contractors", sa.Integer(), nullable=True),
        sa.Column("business_ach_fee", sa.Numeric(), nullable=True),
        sa.Column("contractor_ach_fee", sa.Numeric(), nullable=True),
        sa.Column("transfer_fee", sa.Numeric(), nullable=True),
        sa.Column("tier_code", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "organization", sa.Column("creation_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "organization", sa.Column("next_payment_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "organization", sa.Column("subscription_tier_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "organization", "subscription_tier", ["subscription_tier_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organization", type_="foreignkey")
    op.drop_column("organization", "subscription_tier_id")
    op.drop_column("organization", "next_payment_date")
    op.drop_column("organization", "creation_date")
    op.drop_table("subscription_tier")
    # ### end Alembic commands ###
