"""Add Sessions to database

Revision ID: af784e1ff609
Revises: 2c5c5c0a074b
Create Date: 2021-10-24 15:54:55.941964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af784e1ff609"
down_revision = "2c5c5c0a074b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("session_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    # ### end Alembic commands ###
