"""Add shift tasks, shift notes, job notes, and contractor color. Remove fs_uniquifer from user object

Revision ID: b54b6cf2251c
Revises: 66c63201ce65
Create Date: 2021-12-12 15:51:21.660509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b54b6cf2251c"
down_revision = "66c63201ce65"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shift_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shift_id", sa.Integer(), nullable=True),
        sa.Column("complete", sa.Boolean(), nullable=True),
        sa.Column("time_complete", sa.DateTime(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["shift_id"],
            ["schedule_shift.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "contractor_info", sa.Column("color", sa.String(length=7), nullable=True)
    )
    op.add_column("job", sa.Column("notes", sa.String(), nullable=True))
    op.add_column("schedule_shift", sa.Column("notes", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule_shift", "notes")
    op.drop_column("job", "notes")
    op.drop_column("contractor_info", "color")
    op.drop_table("shift_task")
    # ### end Alembic commands ###
