"""empty message

Revision ID: be2af0a5dc21
Revises: a17cb822d259
Create Date: 2021-01-09 19:58:40.713795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2af0a5dc21'
down_revision = 'a17cb822d259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'manager_id')
    # ### end Alembic commands ###
