"""Add UserLocation table

Revision ID: c409fbcb411b
Revises: f37b38747fee
Create Date: 2021-12-28 15:07:20.826356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c409fbcb411b"
down_revision = "f37b38747fee"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("longitude", sa.Float(precision=32), nullable=True),
        sa.Column("latitude", sa.Float(precision=32), nullable=True),
        sa.Column("precision", sa.Integer(), nullable=True),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_location")
    # ### end Alembic commands ###
