"""Restructured shifts for both timeclock and schedule

Revision ID: c4b3bcb55b78
Revises: f6ac13bef0c8
Create Date: 2021-01-02 17:14:51.297857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4b3bcb55b78'
down_revision = 'f6ac13bef0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_clock_shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_begin', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('time_begin', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('site_location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shift')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_begin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('site_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], name='shift_employee_id_fkey'),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='shift_job_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shift_pkey')
    )
    op.drop_table('schedule_shift')
    op.drop_table('time_clock_shift')
    # ### end Alembic commands ###
