"""Dev Upgrade

Revision ID: d48eeeb8f204
Revises: 042d5ac8a66d
Create Date: 2021-08-25 18:01:03.691764

"""
from typing import ByteString
from app.models import User
from sqlalchemy.orm import Session
import uuid
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d48eeeb8f204"
down_revision = "042d5ac8a66d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    session = Session(bind=conn)
    op.add_column(
        "organization",
        sa.Column("dwolla_customer_url", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "user", sa.Column("dwolla_customer_url", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "user", sa.Column("fs_uniquifier", sa.String(length=255), nullable=True)
    )
    for item in session.query(User).filter_by(fs_uniquifier=None):
        item.fs_uniquifier = uuid.uuid4().hex
    session.commit()
    op.create_unique_constraint(None, "user", ["fs_uniquifier"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "fs_uniquifier")
    op.drop_column("user", "dwolla_customer_url")
    op.drop_column("organization", "dwolla_customer_url")
    # ### end Alembic commands ###
