"""empty message

Revision ID: e764e88ee5fe
Revises: b401e831306c
Create Date: 2022-01-08 16:16:48.363853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e764e88ee5fe"
down_revision = "b401e831306c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "push_registration", ["registration_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "push_registration", type_="unique")
    # ### end Alembic commands ###
