"""Add active flag to job

Revision ID: f36449bb7216
Revises: 7f73c0aa089c
Create Date: 2021-01-17 00:49:49.615464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36449bb7216'
down_revision = '7f73c0aa089c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'active')
    # ### end Alembic commands ###
