"""Add timeclock history and current state to schedule shift object.

Revision ID: f37b38747fee
Revises: e90a807d730c
Create Date: 2021-12-21 15:46:12.375034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f37b38747fee'
down_revision = 'e90a807d730c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_shift', sa.Column('clock_state', sa.Enum('clock_in', 'clock_out', 'start_break', 'end_break', name='timeclockaction'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_shift', 'clock_state')
    # ### end Alembic commands ###
