"""Add job details

Revision ID: f57b5bd952b4
Revises: e764e88ee5fe
Create Date: 2022-01-09 00:10:00.958923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f57b5bd952b4"
down_revision = "e764e88ee5fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("restrict_by_code", sa.Boolean(), nullable=True))
    op.add_column("job", sa.Column("restrict_by_location", sa.Boolean(), nullable=True))
    op.add_column("job", sa.Column("restrict_by_time", sa.Boolean(), nullable=True))
    op.add_column(
        "job", sa.Column("restrict_by_time_window", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "restrict_by_time_window")
    op.drop_column("job", "restrict_by_time")
    op.drop_column("job", "restrict_by_location")
    op.drop_column("job", "restrict_by_code")
    # ### end Alembic commands ###
