"""Added consultant code for clockin verification

Revision ID: f6ac13bef0c8
Revises: f9cd376f1894
Create Date: 2021-01-02 03:45:20.768692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ac13bef0c8'
down_revision = 'f9cd376f1894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('consultant_code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'consultant_code')
    # ### end Alembic commands ###
