"""Add date created to payment. Add job_id to invoice

Revision ID: fc841b035bd6
Revises: 463db72f6333
Create Date: 2022-02-23 20:37:17.174128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fc841b035bd6"
down_revision = "463db72f6333"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoice", sa.Column("job_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "invoice", "job", ["job_id"], ["id"])
    op.add_column("payment", sa.Column("date_created", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payment", "date_created")
    op.drop_constraint(None, "invoice", type_="foreignkey")
    op.drop_column("invoice", "job_id")
    # ### end Alembic commands ###
