"""empty message

Revision ID: fe9514fbeda7
Revises: 28da187eabc2
Create Date: 2021-01-15 15:28:02.444010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9514fbeda7'
down_revision = '28da187eabc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_clock', sa.Column('timecard_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'time_clock', 'time_card', ['timecard_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_clock', type_='foreignkey')
    op.drop_column('time_clock', 'timecard_id')
    # ### end Alembic commands ###
